### ISSUE TITLE
set-output command is deprecated

### ISSUE THREAD

**Issue by DaveKeehl** [PlasmoHQ/soft-secret#19]
I recently used this GitHub action and I got the following warning:

"The set-output command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/"

**Comment by louisgv** [comment]
Done in https://github.com/PlasmoHQ/soft-secret/releases/tag/v1.0.1
